apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: kyverno
  version: 3.5.2
  repo: https://kyverno.github.io/kyverno/
  valuesFile: values.yaml

resources:
- test.yaml

namespace: kyverno

enableHelm: true
