image:
  rootless: true
persistence:
  storageClass: longhorn
postgresql-ha:
  enabled: false
postgresql:
  enabled: true
redis-cluster:
  enabled: false
redis:
  enabled: true
parameters:
- name: gitea.config.server.ROOT_URL
  value: https://gitea.redcomet.ca
- name: gitea.config.server.DOMAIN
  value: gitea.redcomet.ca
- name: gitea.config.server.SSH_DOMAIN
  value: gitea.redcomet.ca