image:
  # -- Image registry
  registry:
  # If you want to manage the registry you should remove it from the repository
  # registry: ghcr.io
  # repository: kyverno/kyverno
  # -- Image repository
  repository: registry1.ro.taneja/ironbank/nirmata/kyverno
  # -- Image tag
  # Defaults to appVersion in Chart.yaml if omitted
  tag: # replaced in e2e tests
  # -- Image pull policy
  pullPolicy: IfNotPresent
  # -- Image pull secrets
  pullSecrets: []