apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: openshift-gitops
spec:
  destination:
    namespace: gitea
    server: https://kubernetes.default.svc
  source:
    path: components/gitea
    repoURL: https://github.com/rohittaneja0/kustomize-helm-poc.git
    targetRevision: HEAD
  sources:
    - chart: gitea
      helm:
        valueFiles:
          - $values/values/democratic-csi/k0s-values.yaml
      repoURL: https://dl.gitea.com/charts/
    - kustomize:
        namespace: gitea
      path: components/gitea
      repoURL: https://github.com/rohittaneja0/kustomize-helm-poc
      targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true