apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: openshift-gitops
spec:
  destination:
    namespace: kyverno
    server: https://kubernetes.default.svc
  source:
    path: components/kyverno
    repoURL: https://github.com/rohittaneja0/kustomize-helm-poc
    targetRevision: HEAD
  sources:
    - chart: kyverno
      helm:
        valueFiles:
        - $values/values/kyverno/values.yaml
      repoURL: https://kyverno.github.io/kyverno/
      path: kyverno
      targetRevision: 3.5.2
    - kustomize:
        namespace: kyverno
      path: components/kyverno
      repoURL: https://github.com/rohittaneja0/kustomize-helm-poc
      targetRevision: HEAD
      ref: values
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
